### ISSUE TITLE
BUG: Where yeti

### ISSUE THREAD

**Issue by Ketho** [Ghostopheles/Datamine#22] opened 2024-08-26 11:14 UTC
I turned into a [big yeti](https://www.wowhead.com/item=147884/tranquil-mechanical-yeti-costume) and Datamine could not find my player actor 🥶
```
Message: .../Modules/Unified/Templates/ModelScene/ModelScene.lua:1079: attempt to index local 'actor' (a nil value)
Time: Mon Aug 26 13:10:22 2024
Count: 4
Stack: .../Modules/Unified/Templates/ModelScene/ModelScene.lua:1079: attempt to index local 'actor' (a nil value)
[string "@Interface/AddOns/Datamine/Modules/Unified/Templates/ModelScene/ModelScene.lua"]:1079: in function `UpdateOutfit'
[string "@Interface/AddOns/Datamine/Modules/Unified/Templates/ModelScene/ModelScene.lua"]:986: in function <.../Modules/Unified/Templates/ModelScene/ModelScene.lua:975>
```

![image](https://github.com/user-attachments/assets/5afbb6a0-68b5-403b-8a59-30f9e9da17fc)

**Comment by Ghostopheles** [comment] 2024-08-26 11:18
what in the heck

**Comment by Ghostopheles** [comment] 2024-12-19 11:44
I'm entirely unable to reproduce this and I think the error was unrelated to the yet in the first place, and was fixed by other changes.

**Closed as completed by Ghostopheles** 2024-12-19 11:44 UTC
Labels: bug
